### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by kimimaru4000** [abhi18av/Alda-VsCode#2]
Thanks so much for making this extension! I've just learned about alda and love how simple the language is. This extension makes it much easier to write alda code.

That said, I noticed there's no license on this project, which means [exclusive copyright law applies](https://choosealicense.com/no-permission/). In simple terms, it's not clear if I'm even allowed to use this extension since there's no license explaining my permissions regarding the software.

On your convenience, can you please add a license to this project? Thank you very much!

**Comment by abhi18av** [comment]
Hi @kimimaru4000 ,

Thanks for trying out this extension!

Sure, I have added the MPL license, which can be observed here https://github.com/abhi18av/Alda-VsCode/blob/master/LICENSE 

If you open up that link above it clarifies that the following is permitted ✅ 

- Commercial use
- Modification
- Distribution
- Patent use
- Private use 

I'll be closing the issue as the license has been added, if you have further questions please do let me know 😊
